# Generated by Django 3.2.16 on 2024-06-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
