# Generated by Django 3.2.16 on 2024-06-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_project_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
