# Generated by Django 3.2.16 on 2024-06-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customusermodel_teams'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUserModel',
        ),
    ]
