# Generated by Django 3.2.16 on 2024-06-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0020_alter_user_team'),
        ('home', '0005_delete_customusermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
